version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development
    command: go run cmd/api/main.go
    restart: unless-stopped 